export const OPEN_LOGIN_DIALOG = 'OPEN_LOGIN_DIALOG';
export const CLOSE_LOGIN_DIALOG = 'CLOSE_LOGIN_DIALOG';
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const OPEN_LOGOUT_DIALOG = 'OPEN_LOGOUT_DIALOG';
export const CLOSE_LOGOUT_DIALOG = 'CLOSE_LOGOUT_DIALOG';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const KEY_USERNAME = 'KEY_USERNAME';
export const KEY_PASSWORD = 'KEY_PASSWORD';

export const SHOW_DELETE_ARTICLE_MODAL = 'SHOW_DELETE_ARTICLE_MODAL';
export const HIDE_DELETE_ARTICLE_MODAL = 'HIDE_DELETE_ARTICLE_MODAL';

export const REQUEST_DELETE_ARTICLE = 'REQUEST_DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';
