// Create
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SAVED = 'ADD_ARTICLE_SAVED';
export const ADD_ARTICLE_FAILED = 'ADD_ARTICLE_FAILED';
// Edit
export const FETCH_EDIT_ARTICLE = 'FETCH_EDIT_ARTICLE';
export const UPDATE_EDIT_ARTICLE = 'UPDATE_EDIT_ARTICLE';
export const EDIT_ARTICLE = 'EDIT_ARTICLE';
export const EDIT_ARTICLE_SAVED = 'EDIT_ARTICLE_SAVED';
export const EDIT_ARTICLE_FAILED = 'EDIT_ARTICLE_FAILED';
// Form
export const NEW_KEY_ARTICLE_NAME = 'NEW_KEY_ARTICLE_NAME';
export const NEW_KEY_ARTICLE_SUMMARY = 'NEW_KEY_ARTICLE_SUMMARY';
export const NEW_KEY_ARTICLE_CONTENT = 'NEW_KEY_ARTICLE_CONTENT';
export const NEW_KEY_ARTICLE_IMG = 'NEW_KEY_ARTICLE_IMG';

export const EDIT_KEY_ARTICLE_NAME = 'EDIT_KEY_ARTICLE_NAME';
export const EDIT_KEY_ARTICLE_SUMMARY = 'EDIT_KEY_ARTICLE_SUMMARY';
export const EDIT_KEY_ARTICLE_CONTENT = 'EDIT_KEY_ARTICLE_CONTENT';
export const EDIT_KEY_ARTICLE_IMG = 'EDIT_KEY_ARTICLE_IMG';

// Markdown
export const REQUEST_PREVIEW = 'REQUEST_PREVIEW';
export const UPDATE_PREVIEW = 'UPDATE_PREVIEW';
export const REQUEST_PREVIEW_FAILED = 'REQUEST_PREVIEW_FAILED';

export const EDITING_REQUEST_PREVIEW = 'EDITING_REQUEST_PREVIEW';
export const EDITING_UPDATE_PREVIEW = 'EDITING_UPDATE_PREVIEW';
export const EDITING_REQUEST_PREVIEW_FAILED = 'EDITING_REQUEST_PREVIEW_FAILED';
