export const FETCH_PENDING_ARTICLES = 'FETCH_PENDING_ARTICLES';
export const UPDATE_PENDING_ARTICLES = 'UPDATE_PENDING_ARTICLES';
export const FETCH_PENDING_ARTICLES_FAILED = 'FETCH_PENDING_ARTICLES_FAILED';
